feat(ifc): add interfaces
morpho-org/morpho-blue-oracles pull request #51
Opened 2023-11-29 11:10 UTC by Rubilmax

2023-11-29 15:01 UTC, QGarchery requested changes
Accidental change of the submodule I think: it goes to an earlier version of Blue, whereas it was already at the release version

2023-11-29 15:06 UTC, QGarchery commented on src/interfaces/IChainlinkOracle.sol
> +pragma solidity ^0.8.0;
We use `>= 0.5.0` in Blue because we want interfaces to be easily usable. No use in breaking in later versions for example

2023-11-29 16:31 UTC, MerlinEgalite approved these changes

2023-12-04 08:49 UTC, MathisGD approved these changes

2023-12-04 08:49 UTC, MathisGD commented on src/ChainlinkOracle.sol
> +
```suggestion
```

2023-12-04 08:49 UTC, MathisGD commented on src/ChainlinkOracle.sol
> +
```suggestion
```

2023-12-04 08:49 UTC, MathisGD commented on src/ChainlinkOracle.sol
> +
```suggestion
```

2023-12-04 08:49 UTC, MathisGD commented on src/ChainlinkOracle.sol
> +
```suggestion
```

2023-12-04 08:49 UTC, MathisGD commented on src/ChainlinkOracle.sol
> +
```suggestion
```

2023-12-04 08:49 UTC, MathisGD commented on src/ChainlinkOracle.sol
> +
```suggestion
```

2023-12-04 09:28 UTC, Rubilmax commented on src/ChainlinkOracle.sol
> +
😁 pls someone help me protect spaced storage

2023-12-04 09:41 UTC, QGarchery commented on src/ChainlinkOracle.sol
> +
I'm fine with either

2023-12-04 17:14 UTC, MerlinEgalite commented
@Jean-Grimal can you review it please?

2023-12-04 17:17 UTC, Jean-Grimal approved these changes

2023-12-05 09:36 UTC, merged