feat(readme): explaining the oracle creation from the factory
morpho-org/morpho-blue-oracles pull request #86
Opened 2024-03-06 15:19 UTC by tomrpl

Updating the readme, thanks to the `MorphoChainlinkOracleV2Factory`

2024-03-06 15:57 UTC, MerlinEgalite requested changes

2024-03-06 15:57 UTC, MerlinEgalite commented on README.md
> +The `MorphoChainlinkOracleV2` is an oracle that uses Chainlink-compliant feeds to provide price data.
```suggestion
The `MorphoChainlinkOracleV2` is an oracle that uses Chainlink-interfacce-compliant feeds to provide price data.
```

2024-03-06 15:57 UTC, MerlinEgalite commented on README.md
> +A specific implementation, the WstEthStEthExchangeRateChainlinkAdapter, provides the exchange rate between wstETH and stETH using Chainlink. This adapter is designed for precise, decentralized price
```suggestion
A specific implementation, the `WstEthStEthExchangeRateChainlinkAdapter`, provides the exchange rate between wstETH and stETH.
```

2024-03-06 15:57 UTC, MerlinEgalite commented on README.md
> +Deployed on Ethereum Mainnet, this adapter can be found in Ethereum Mainnet at the address [0x905b7dAbCD3Ce6B792D874e303D336424Cdb1421](https://etherscan.io/address/0x905b7dabcd3ce6b792d874e303d33642
```suggestion
Deployed on Ethereum Mainnet, this adapter can be found on Ethereum Mainnet at the address [0x905b7dAbCD3Ce6B792D874e303D336424Cdb1421](https://etherscan.io/address/0x905b7dabcd3ce6b792d874e303d336424cdb1421#code).
```

2024-03-06 15:57 UTC, MerlinEgalite commented on README.md
> +The factory facilitates the easy creation and indexing of MorphoChainlinkOracleV2 oracles. Developed by Morpho Labs, this factory contract streamlines the process of deploying new oracles, catering t
```suggestion
The factory facilitates the easy creation and indexing of `MorphoChainlinkOracleV2` oracles. This factory contract streamlines the process of deploying new oracles, catering to various market pairs without the need for deploying individual contracts manually for each pair.
```

2024-03-06 15:57 UTC, MerlinEgalite commented on README.md
> +To create a new `MorphoChainlinkOracleV2` oracle using the factory, call the createMorphoChainlinkOracleV2 function with the following parameters:
```suggestion
To create a new `MorphoChainlinkOracleV2` oracle using the factory, call the `createMorphoChainlinkOracleV2` function with the following parameters:
```

2024-03-06 15:57 UTC, MerlinEgalite commented on README.md
>  ## Deploy an Oracle
can be moved to usage IMO

2024-03-06 16:24 UTC, Rubilmax commented on README.md
> +A specific implementation, the `WstEthStEthExchangeRateChainlinkAdapter`, provides the exchange rate between wstETH and stETH.
```suggestion
A specific implementation, the `WstEthStEthExchangeRateChainlinkAdapter`, provides the exchange rate between wstETH and stETH as a Chainlink-interface-compliant feed.
```

2024-03-06 16:24 UTC, Rubilmax commented on README.md
> +Deployed on Ethereum Mainnet, this adapter can be found on Ethereum Mainnet at the address [0x905b7dAbCD3Ce6B792D874e303D336424Cdb1421](https://etherscan.io/address/0x905b7dabcd3ce6b792d874e303d33642
```suggestion
This adapter is deployed on Ethereum Mainnet at the address [0x905b7dAbCD3Ce6B792D874e303D336424Cdb1421](https://etherscan.io/address/0x905b7dabcd3ce6b792d874e303d336424cdb1421#code).
```

2024-03-06 16:24 UTC, Rubilmax commented on README.md
> +The factory facilitates the easy creation and indexing of `MorphoChainlinkOracleV2` oracles. This factory contract streamlines the process of deploying new oracles, catering to various market pairs w
```suggestion
The factory facilitates the creation and indexing of `MorphoChainlinkOracleV2` oracles. This factory contract streamlines the process of deploying new oracles, catering to various market pairs without the need to deploy individual contracts manually for each pair.
```

2024-03-06 16:24 UTC, Rubilmax commented on README.md
> +- `salt`: <user-defined value used to make the address unique>,
```suggestion
```json
{
  "baseVault": "0x0000000000000000000000000000000000000000",
  "baseVaultConversionSample": 1,
  "baseFeed1": "0x0000000000000000000000000000000000000000",
  "baseFeed2": "0x0000000000000000000000000000000000000000",
  "baseTokenDecimals": 18,
  "quoteVault": "0x0000000000000000000000000000000000000000",
  "quoteVaultConversionSample": 1,
  "quoteFeed1": "0xEe9F2375b4bdF6387aa8265dD4FB8F16512A1d46",
  "quoteFeed2": "0x0000000000000000000000000000000000000000",
  "quoteTokenDecimals": 6,
  "salt": "user-defined 32 bytes used to make the address unique",
```

```

2024-03-06 17:20 UTC, MerlinEgalite submitted a review, later dismissed

2024-03-07 08:32 UTC, MathisGD commented on README.md
> +## MorphoChainlinkOracleV2Factory
I would not do a separated category for the factory, and just add this to the corresponding oracle part

2024-03-07 08:32 UTC, MathisGD commented on README.md
> +This adapter is deployed on Ethereum Mainnet at the address [0x905b7dAbCD3Ce6B792D874e303D336424Cdb1421](https://etherscan.io/address/0x905b7dabcd3ce6b792d874e303d336424cdb1421#code).
there is no need to say "mainnet" all the time imo
```suggestion
This adapter is deployed on Ethereum at the address [0x905b7dAbCD3Ce6B792D874e303D336424Cdb1421](https://etherscan.io/address/0x905b7dabcd3ce6b792d874e303d336424cdb1421#code).
```

2024-03-07 08:32 UTC, MathisGD commented on README.md
>  - A'/C and B/C are feeds, and there is an exchange rate between A and A'. (typically A=sDAI and A'=DAI).
this has to be adapted

2024-03-07 09:01 UTC, QGarchery approved these changes, later dismissed

2024-03-07 09:01 UTC, QGarchery commented on README.md
> +- `baseVault`: "0x83f20f44975d03b1b09e64809b757c47f942beea",
```suggestion
- `baseVault`: "0x83F20F44975D03b1b09e64809B757c47f942BEeA",
```
to have the correct checksum, as it is the case for the other addresses

2024-03-07 09:46 UTC, MerlinEgalite approved these changes

2024-03-07 09:46 UTC, merged