docs: update readme
morpho-org/morpho-blue-oracles pull request #96
Opened 2024-04-09 14:38 UTC by Jean-Grimal

2024-04-09 15:34 UTC, MerlinEgalite requested changes

2024-04-09 15:34 UTC, MerlinEgalite commented on README.md
>  The factory facilitates the creation and indexing of `MorphoChainlinkOracleV2` oracles. This factory contract streamlines the process of deploying new oracles, catering to various market pairs withou
i think you can delete this part which is useless

2024-04-11 08:45 UTC, QGarchery approved these changes

2024-04-11 08:45 UTC, QGarchery commented on README.md
> +### MorphoChainlinkOracleV2Factory
```suggestion
```
otherwise we have an empty title

2024-04-11 08:45 UTC, QGarchery commented on README.md
> +To deploy a `MorphoChainlinkOracleV2` on the Ethereum mainnet, use the `MorphoChainlinkOracleV2Factory` to create a new oracle. Call the `createMorphoChainlinkOracleV2` function with the following pa
```suggestion
To deploy a `MorphoChainlinkOracleV2` on Ethereum mainnet, use the `MorphoChainlinkOracleV2Factory` to create a new oracle. Call the `createMorphoChainlinkOracleV2` function with the following parameters:
```
[optional]

2024-04-11 08:45 UTC, QGarchery commented on README.md
> +To deploy a `MorphoChainlinkOracleV2` on the Ethereum mainnet, use the `MorphoChainlinkOracleV2Factory` to create a new oracle. Call the `createMorphoChainlinkOracleV2` function with the following pa
Let's put every sentence in a new line. It's easier that way to see the diff when doing big changes

2024-04-12 08:23 UTC, MerlinEgalite approved these changes

2024-04-12 13:35 UTC, QGarchery approved these changes

2024-04-23 15:32 UTC, MathisGD commented on README.md
> +To deploy a `MorphoChainlinkOracleV2` on the Ethereum mainnet, use the `MorphoChainlinkOracleV2Factory` to create a new oracle.
```suggestion
To deploy a `MorphoChainlinkOracleV2` on Ethereum, it is highly recommended to use the factory `MorphoChainlinkOracleV2Factory`.
```

2024-04-23 15:32 UTC, MathisGD commented on README.md
> +The Ethereum Mainnet address of this factory is [0x3A7bB36Ee3f3eE32A60e9f2b33c1e5f2E83ad766](https://etherscan.io/address/0x3a7bb36ee3f3ee32a60e9f2b33c1e5f2e83ad766#code).
```suggestion
The address on Ethereum of this factory is [0x3A7bB36Ee3f3eE32A60e9f2b33c1e5f2E83ad766](https://etherscan.io/address/0x3a7bb36ee3f3ee32a60e9f2b33c1e5f2e83ad766#code).
```

2024-04-23 15:32 UTC, MathisGD commented on README.md
> +Call the `createMorphoChainlinkOracleV2` function with the following parameters:
```suggestion
To do so, call the `createMorphoChainlinkOracleV2` function with the following parameters:
```

2024-04-23 15:32 UTC, MathisGD commented on README.md
> +**Warning:** If there is an ERC4626-compliant vault for `baseVault` or `quoteVault`, the `baseTokenDecimals` or `quoteTokenDecimals` are still the decimals of the asset in the vault, and not the deci
```suggestion
**Warning:** If there is an ERC4626-compliant vault for `baseVault` or `quoteVault`, the `baseTokenDecimals` or `quoteTokenDecimals` are still the decimals of the underlying asset of the vault, and not the decimals of the Vault itself.
```

2024-04-23 15:32 UTC, MathisGD commented on README.md
> +E.g: for a MetaMorpho WETH vault, as `baseVault`, the `baseTokenDecimals` is 18 as WETH has 18 decimals.
metamorpho also has 18 decimals (and most vaults do), so the example is not perfect

to me we can just remove it

2024-04-26 16:46 UTC, MerlinEgalite commented
Apply changes and merged, PR pending for too long

2024-04-26 16:47 UTC, merged